export const GET_EMPLOYEES_LIST = "GET_EMPLOYEES_LIST";
export const GET_EMPLOYEES_LIST_SUCCESS = "GET_EMPLOYEES_LIST_SUCCESS";
export const GET_EMPLOYEES_LIST_FAIL = "GET_EMPLOYEES_LIST_FAIL";

export const SET_LOADING = "SET_LOADING";
